//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Дипломная_работа
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orders()
        {
            this.transport = new HashSet<transport>();
        }
    
        public int Code_order { get; set; }
        public int Code_client { get; set; }
        public int Code_worker { get; set; }
        public string Type_gruz { get; set; }
        public string Razmer_gruz { get; set; }
        public string Ves_gruz { get; set; }
        public string Date_sdachi { get; set; }
        public string City { get; set; }
    
        public virtual client client { get; set; }
        public virtual worker worker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transport> transport { get; set; }
    }
}
