//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Дипломная_работа
{
    using System;
    using System.Collections.Generic;
    
    public partial class transport
    {
        public int Code_transport { get; set; }
        public int Code_order { get; set; }
        public int Code_auto { get; set; }
        public int Code_voditel { get; set; }
        public string City { get; set; }
        public string Date_otpr { get; set; }
        public string Count { get; set; }
    
        public virtual autopark autopark { get; set; }
        public virtual orders orders { get; set; }
        public virtual voditel voditel { get; set; }
    }
}
