//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Дипломная_работа
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int Code { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int Code_worker { get; set; }
        public string Role { get; set; }
        public string Email { get; set; }
        public string CodeVost { get; set; }
    
        public virtual worker worker { get; set; }
    }
}
